### ISSUE TITLE
Error on generating VCFs

### ISSUE THREAD

**Issue by nuin** [alliance-genome/agr_file_generator#17]
Hi 

I have been working on this code for this past week and was able to modify a couple of things that changed on the database (HGVS nomenclature field name change and Assembly location change) and add some simple enhancements that seemed to be on the pipeline anyway.

But now I am stuck on an error that is taking a little bit more time to fix, and it seems that is somewhat correlated to the DB items, more specifically on mouse variants.

The error

```python
python app.py                                             [ruby-2.6.4p104]
Traceback (most recent call last):
  File "app.py", line 132, in <module>
    main()
  File "app.py", line 26, in main
    generate_vcf_files(generated_files_folder, fasta_sequences_folder, skip_chromosomes)
  File "app.py", line 58, in generate_vcf_files
    gvf.generate_files(skip_chromosomes=skip_chromosomes)
  File "/Users/nuin/Downloads/agr_file_generator_original/src/vcf_file_generator.py", line 142, in generate_files
    filename = assembly + '-' + self.database_version  + '.vcf'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

`unsupported operand type(s) for +: 'NoneType' and 'str'` seems tp be an error when something is compared to `None` on function returns, but one or more endpoints of the function is missing a value (None or something else).

The problem is occurring on this section on `vcd_file_generator.py`

```python
                    adjust_varient = partial(self._adjust_variant)
                    adjusted_variants = filter(None, map(adjust_varient, variants))
                    for variant in sorted(adjusted_variants, key=itemgetter('POS')):
                        self._add_variant_to_vcf_file(vcf_file, variant)
```
 which is connected to 

```python
    def _adjust_variant(self, variant):
        so_term = variant['soTerm']
        start_pos = variant['start']
        variant['POS'] = start_pos - 1 if so_term == 'insertion' else start_pos
        if so_term == 'deletion':
            if variant['genomicReferenceSequence'] == '':
                logger.error('No reference sequence for variant Id: %r', variant['ID'])
                return None
            if variant['genomicVariantSequence'] == '':
                self._add_padded_base_to_variant(variant, 'deletion')
        elif so_term == 'insertion':
            if variant['genomicReferenceSequence'] != '':
                logger.error('Insertion Variant reference sequence is populated '
                             'when it should not be in '
                             'variant ID: %r',
                             variant['ID'])
                return None
            if variant['genomicVariantSequence'] == '':
                return None
            self._add_padded_base_to_variant(variant, 'insertion')
        elif so_term == 'point_mutation':
            variant['POS'] = variant['start']
        elif so_term == 'MNV':
            variant['POS'] = variant['end']
        else:
            logger.fatal('New SoTerm that We need to add logic for: %r', so_term)
            return None
        return variant
```

In my modified code for debugging, I was able to pinpoint the problem when generating `GRCm38-test.vcf`, but I wasn't able to define the exact variant that is not returning a value from `_adjust_variant`.

Any help appreciated.

**Comment by nuin** [comment]
In fact the error was on MNV type variants with no POS/end assigned in the DB

```
elif so_term == 'MNV':
            variant['POS'] = variant['end']
```

if `variant['end']` is None the variant returned will have a None in the dict, will not be filtered out and will generate the error downstream in the function.
